services:
  nginx:
    image: nginx:inception
    container_name: ${CONTAINER_NAME}-nginx
    build: ./requirements/nginx
    env_file: .env
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
      - adminer
      - static

  mariadb:
    image: mariadb:inception
    container_name: ${CONTAINER_NAME}-mariadb
    build: ./requirements/mariadb
    env_file: .env
    secrets:
      - db_password
      - db_root_password
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  wordpress:
    image: wordpress:inception
    container_name: ${CONTAINER_NAME}-wordpress
    build: ./requirements/wordpress
    env_file: .env
    secrets:
      - db_password
      - credentials
      - wp_user_password
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
      - redis

  redis:
    image: redis:inception
    container_name: ${CONTAINER_NAME}-redis
    build: ./requirements/bonus/redis
    restart: unless-stopped
    networks:
      - inception

  adminer:
    image: adminer:inception
    container_name: ${CONTAINER_NAME}-adminer
    build: ./requirements/bonus/adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - inception
    depends_on:
      - mariadb

  static:
    image: static:inception
    container_name: ${CONTAINER_NAME}-static
    build: ./requirements/bonus/static
    restart: unless-stopped
    ports:
      - "8082:8082"
    networks:
      - inception



volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/mariadb

networks:
  inception:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
