services:
  nginx:
    container_name: ${CONTAINER_NAME}-nginx
    build: ./requirements/nginx
    env_file: .env
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception



volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/wordpress

networks:
  inception:
    driver: bridge
